In [ ]:
import torch
torch.__version__

'2.0.0+cu118'

In [ ]:
# Create a scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
# Check dimeensions
scalar.ndim

0

In [ ]:
# Retrieve item from tensor
scalar.item()

7

In [ ]:
# Create a vector

vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
# Check dimensions
vector.ndim

1

In [ ]:
# Check shape

vector.shape

torch.Size([2])

In [ ]:
# Create a matrix
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
# Check dimensions
MATRIX.ndim

2

In [ ]:
# Check shape
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# Create a tensor
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
# Check dimensions
TENSOR.ndim

3

In [ ]:
# Check shape
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
# Create a random tensor of size 3 x 4
random_tensor = torch.rand(size=(3,4))
random_tensor, random_tensor.dtype

(tensor([[0.4253, 0.5451, 0.8420, 0.1276],
         [0.2975, 0.3177, 0.8844, 0.5712],
         [0.7666, 0.7216, 0.4680, 0.1971]]),
 torch.float32)

In [ ]:
# Create a zero tensor
zeros = torch.zeros(size=(3,4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [ ]:
# Create a ones tensor
ones = torch.ones(size=(3,4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [ ]:
# Create a range of values
range_hundred = torch.arange(start=0, end=100, step=10)
range_hundred

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# Create a zero tensor with same shape as range tensor
hundreds_zero = torch.zeros_like(input=range_hundred)
hundreds_zero

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
# Create different float datatypes

float_32_tensor = torch.tensor([3.0,6.0,9.0],dtype=None,device=None,requires_grad=False)

float_16_tensor = torch.tensor([3.0,6.0,9.0],dtype=torch.float16,device=None,requires_grad=False)

float_32_tensor.dtype, float_32_tensor.device, float_16_tensor.dtype, float_16_tensor.device

(torch.float32, device(type='cpu'), torch.float16, device(type='cpu'))

In [ ]:
# Perform addition

sample_tensor = torch.rand(size=(1,3))
sample_tensor, sample_tensor + 10

(tensor([[0.5122, 0.2949, 0.5908]]), tensor([[10.5122, 10.2949, 10.5908]]))

In [ ]:
# Perform multiplication
sample_tensor * 10

tensor([[5.1215, 2.9490, 5.9083]])

In [ ]:
# Perform subtraction and reassign tensor
sample_tensor = sample_tensor - 10
sample_tensor

tensor([[-9.4878, -9.7051, -9.4092]])

In [ ]:
# Perform addition and reassign tensor
sample_tensor = sample_tensor + 10
sample_tensor

tensor([[0.5122, 0.2949, 0.5908]])

In [ ]:
# Use torch function for multiplication
torch.multiply(sample_tensor,10)

tensor([[5.1215, 2.9490, 5.9083]])

In [ ]:
# Element-wise multiplication
sample_tensor * sample_tensor

tensor([[0.2623, 0.0870, 0.3491]])

In [ ]:
# Matrix multiplication (1x3) @ (3x1)
torch.matmul(sample_tensor, sample_tensor.T)

tensor([[0.6983]])

In [ ]:
# Matrix multiplication (3x1) @ (1x3)
torch.matmul(sample_tensor.T, sample_tensor)

tensor([[0.2623, 0.1510, 0.3026],
        [0.1510, 0.0870, 0.1742],
        [0.3026, 0.1742, 0.3491]])

# Playing with linear layers

In [ ]:
#### Playing with linear layers ####

# Set seed
torch.manual_seed(42)

# Uses matrix multiplication
# in_features is the inner dimension of the input
# out_features is the desired inner dimension of the output
# bias determines whether a bias variable is considered with shape out_features
# weights are learned in the shape (out_features,in_features)
linear = torch.nn.Linear(in_features=2, out_features=6)

tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

output = linear(tensor_A)

print(f"Input shape: {tensor_A.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")


Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


# Using aggregate functions

In [ ]:
#### Using aggregate functions ####

# create a tensor

x = torch.arange(0,100,10)

print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

# Use in-built torch methods

torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


(tensor(90), tensor(0), tensor(45.), tensor(450))

In [ ]:
# Positional functions

# Returns index of max and min values
print(f"Index where max value occurs: {x.argmax()}")
print(f"Index where min value occurs: {x.argmin()}")

Index where max value occurs: 9
Index where min value occurs: 0


# Shape-related operations

In [ ]:
#### Shape-related operations ####

x = torch.arange(1.0,8.0)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [ ]:
# Add extra dimension

x_reshaped = x.reshape(1,7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [ ]:
# Change the view

z = x.view(1,7)
# viewing the tensor does not change original tensor
z, z.shape, x, x.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]),
 torch.Size([1, 7]),
 tensor([1., 2., 3., 4., 5., 6., 7.]),
 torch.Size([7]))

In [ ]:
# changing the view changes original tensor

z[:,0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

In [ ]:
# stack tensors

x_stacked_0 = torch.stack([x,x,x,x,x],dim=0)
x_stacked_1 = torch.stack([x,x,x,x,x],dim=1)

x_stacked_0,x_stacked_0.shape, x_stacked_1,x_stacked_1.shape

(tensor([[5., 2., 3., 4., 5., 6., 7.],
         [5., 2., 3., 4., 5., 6., 7.],
         [5., 2., 3., 4., 5., 6., 7.],
         [5., 2., 3., 4., 5., 6., 7.],
         [5., 2., 3., 4., 5., 6., 7.]]),
 torch.Size([5, 7]),
 tensor([[5., 5., 5., 5., 5.],
         [2., 2., 2., 2., 2.],
         [3., 3., 3., 3., 3.],
         [4., 4., 4., 4., 4.],
         [5., 5., 5., 5., 5.],
         [6., 6., 6., 6., 6.],
         [7., 7., 7., 7., 7.]]),
 torch.Size([7, 5]))

In [ ]:
# remove extra dimension only if it is 1

x_squeezed = x_reshaped.squeeze()
x_squeezed, x_squeezed.shape

(tensor([5., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [ ]:
# Add a dimension of 1

x_unsqueezed_0 = x_squeezed.unsqueeze(dim=0)
x_unsqueezed_1 = x_squeezed.unsqueeze(dim=1)

x_unsqueezed_0, x_unsqueezed_0.shape, x_unsqueezed_1, x_unsqueezed_1.shape

(tensor([[5., 2., 3., 4., 5., 6., 7.]]),
 torch.Size([1, 7]),
 tensor([[5.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.]]),
 torch.Size([7, 1]))

In [ ]:
# Change the order of dimensions

x_original = torch.rand(size=(224,224,3))
x_permuted = x_original.permute(2,0,1) # permute returns a new view
x_original.shape, x_permuted.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

# Indexing

In [ ]:
#### Indexing ####

x = torch.arange(1,10).reshape(1,3,3)
x, x.shape, x.ndim

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]),
 3)

In [ ]:
# Indexing goes from outer to inner dimension

x[0], x[0][0], x[0][0][0]

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 tensor([1, 2, 3]),
 tensor(1))

In [ ]:
# Get all values in a dimension

x[:,0], x[:,:,1], x[:,1,1]

(tensor([[1, 2, 3]]), tensor([[2, 5, 8]]), tensor([5]))

# Reproducibility

In [ ]:
#### Reproducibility ####

random_a = torch.rand(3,4)
random_b = torch.rand(3,4)
random_a == random_b

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [ ]:
torch.manual_seed(42)
random_c = torch.rand(3,4)

torch.manual_seed(42)
random_d = torch.rand(3,4)

random_c == random_d

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [ ]:
!nvidia-smi

Wed May 10 11:35:58 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA A100-SXM...  Off  | 00000000:00:04.0 Off |                    0 |
| N/A   29C    P0    42W / 400W |      0MiB / 40960MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
torch.cuda.is_available()

True

In [ ]:
# set device the correct way

device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# count number of devices being used
torch.cuda.device_count()

1

In [ ]:
# put tensor on a GPU

tensor = torch.tensor([1,2,3]) # default is on CPU

print(tensor, tensor.device)

tensor_gpu = tensor.to(device)

print(tensor_gpu, tensor_gpu.device)

tensor([1, 2, 3]) cpu
tensor([1, 2, 3], device='cuda:0') cuda:0


In [ ]:
# move tensor back to CPU using numpy

import numpy as np

tensor_gpu.cpu().numpy() # creates a copy in CPU

array([1, 2, 3])

# Exercises

In [ ]:
#### Exercises ####

# Qn 2: Create a random tensor with shape (7, 7)

qn2 = torch.rand(size=(7,7))
qn2

tensor([[0.8694, 0.5677, 0.7411, 0.4294, 0.8854, 0.5739, 0.2666],
        [0.6274, 0.2696, 0.4414, 0.2969, 0.8317, 0.1053, 0.2695],
        [0.3588, 0.1994, 0.5472, 0.0062, 0.9516, 0.0753, 0.8860],
        [0.5832, 0.3376, 0.8090, 0.5779, 0.9040, 0.5547, 0.3423],
        [0.6343, 0.3644, 0.7104, 0.9464, 0.7890, 0.2814, 0.7886],
        [0.5895, 0.7539, 0.1952, 0.0050, 0.3068, 0.1165, 0.9103],
        [0.6440, 0.7071, 0.6581, 0.4913, 0.8913, 0.1447, 0.5315]])

In [ ]:
# Qn 3: Perform a matrix multiplication on the tensor from 
# 2 with another random tensor with shape (1, 7)

another = torch.rand(size=(1,7))

qn3 = qn2 @ another.T
qn3

tensor([[1.9625],
        [1.0950],
        [0.9967],
        [1.8910],
        [1.9205],
        [1.0674],
        [1.6949]])

In [ ]:
# Qn 4: Set the random seed to 0 and do exercises 2 & 3 over again.

torch.manual_seed(0)
qn2 = torch.rand(size=(7,7))
another = torch.rand(size=(1,7))
qn3 = qn2 @ another.T
qn2, qn3

(tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
         [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
         [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
         [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
         [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
         [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
         [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]]),
 tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]))

In [ ]:
# Qn 5: Speaking of random seeds, we saw how to set it with 
# torch.manual_seed() but is there a GPU equivalent?
# If there is, set the GPU random seed to 1234.

torch.cuda.manual_seed(1234)

In [ ]:
# Qn 6: Create two random tensors of shape (2, 3) 
# and send them both to the GPU (you'll need access to a GPU 
# for this). Set torch.manual_seed(1234) when creating the 
# tensors (this doesn't have to be the GPU random seed).

torch.manual_seed(1234)

rand_1 = torch.rand(size=(2,3)).to(device)
rand_2 = torch.rand(size=(2,3)).to(device)
rand_1.device, rand_2.device

(device(type='cuda', index=0), device(type='cuda', index=0))

In [ ]:
# Qn 7: Perform a matrix multiplication on the tensors you 
# created in 6 (again, you may have to adjust the shapes of 
# one of the tensors).

qn7 = rand_1 @ rand_2.T

In [ ]:
# Qn 8: Find the maximum and minimum values of the output of 7.

qn7.max(), qn7.min()

(tensor(0.5617, device='cuda:0'), tensor(0.3647, device='cuda:0'))

In [ ]:
# Qn 9: Find the maximum and minimum index values of the output of 7.

qn7.argmax(), qn7.argmin()

(tensor(3, device='cuda:0'), tensor(0, device='cuda:0'))

In [ ]:
# Make a random tensor with shape (1, 1, 1, 10) and then 
# create a new tensor with all the 1 dimensions removed to be 
# left with a tensor of shape (10). Set the seed to 7 when 
# you create it and print out the first tensor and it's shape 
# as well as the second tensor and it's shape.

torch.manual_seed(7)
qn10 = torch.rand(size=(1,1,1,10))
print(qn10, qn10.shape)
qn10 = qn10.squeeze()
print(qn10, qn10.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
